In [15]:
%%script echo skipping

# Initialize Otter
import otter
grader = otter.Notebook("lab01.ipynb")

skipping


# Lab 01

Welcome to the first lab of Data 100! This lab is meant to help you familiarize yourself with JupyterHub, review Python and `numpy`, and introduce you to `matplotlib`, a Python visualization library. 

To receive credit for a lab, answer all questions correctly and submit before the deadline.

**This lab is due Tuesday, January 25 at 11:59 PM.**

### Lab Walk-Through

In addition to the lab notebook, we have also released a prerecorded walk-through video of the lab. We encourage you to reference this video as you work through the lab. Run the cell below to display the video.

Video 3: https://www.youtube.com/watch?v=66VPtNULU48&list=PLQCcNQgUcDfrhStFqvgpvLNhOS43bnSQq&index=3

In [16]:
%%script echo skipping

from IPython.display import YouTubeVideo
YouTubeVideo("PS7lPZUnNBo", list = 'PLQCcNQgUcDfrhStFqvgpvLNhOS43bnSQq', listType = 'playlist')



skipping


### Collaboration Policy

Data science is a collaborative activity. While you may talk with others about the labs, we ask that you **write your solutions individually**. If you do discuss the assignments with others please **include their names** below. (That's a good way to learn your classmates' names.)

**Collaborators**: *list collaborators here*

---
## Part 1: Jupyter Tips


### Viewing Documentation

To output the documentation for a function, use the `help` function.

In [17]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



You can also use Jupyter to view function documentation inside your notebook. The function must already be defined in the kernel for this to work.

Below, click your mouse anywhere on the `print` block below and use `Shift` + `Tab` to view the function's documentation. 

In [18]:
print('Welcome to Data 100.')

Welcome to Data 100.


### Importing Libraries and Magic Commands

In Data 100, we will be using common Python libraries to help us process data. By convention, we import all libraries at the very top of the notebook. There are also a set of standard aliases that are used to shorten the library names. Below are some of the libraries that you may encounter throughout the course, along with their respective aliases.

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
%matplotlib inline

## Dal je ovo sad tu nakon Google?

`%matplotlib inline` is a [Jupyter magic command](https://ipython.readthedocs.io/en/stable/interactive/magics.html) that configures the notebook so that Matplotlib displays any plots that you draw directly in the notebook rather than to a file, allowing you to view the plots upon executing your code. (Note: In practice, this is no longer necessary, but we're showing it to you now anyway.)

Another useful magic command is `%%time`, which times the execution of that cell. You can use this by writing it as the first line of a cell. (Note that `%%` is used for *cell magic commands* that apply to the entire cell, whereas `%` is used for *line magic commands* that only apply to a single line.)

In [20]:
%%time

lst = []
for i in range(100):
    lst.append(i)

CPU times: user 36 µs, sys: 5 µs, total: 41 µs
Wall time: 49.8 µs


### Keyboard Shortcuts

Even if you are familiar with Jupyter, we strongly encourage you to become proficient with keyboard shortcuts (this will save you time in the future). To learn about keyboard shortcuts, go to **Help --> Keyboard Shortcuts** in the menu above. 

Here are a few that we like:
1. `Ctrl` + `Return` (or `Cmd` + `Return` on Mac): *Evaluate the current cell*
1. `Shift` + `Return`: *Evaluate the current cell and move to the next*
1. `ESC` : *command mode* (may need to press before using any of the commands below)
1. `a` : *create a cell above*
1. `b` : *create a cell below*
1. `dd` : *delete a cell*
1. `z` : *undo the last cell operation*
1. `m` : *convert a cell to markdown*
1. `y` : *convert a cell to code*

---
## Part 2: Prerequisites

It's time to answer some review questions. Each question has a response cell directly below it. Most response cells are followed by a test cell that runs automated tests to check your work. Please don't delete questions, response cells, or test cells. You won't get credit for your work if you do.

If you have extra content in a response cell, such as an example call to a function you're implementing, that's fine. Also, feel free to add cells between the question cells and test cells (or the next cell, for questions without test cases). Any extra cells you add will be considered part of your submission. Finally, when you finish an assignment, make sure to "restart and run all cells" to ensure everything works properly. 

Note that for labs, ontime submissions that pass all the test cases will receive full credit. However for homeworks, test cells don't always confirm that your response is correct. They are meant to give you some useful feedback, but it's your responsibility to ensure your response answers the question correctly. There may be other tests that we run when scoring your notebooks. We **strongly recommend** that you check your solutions yourself rather than just relying on the test cells.

### Python

Python is the main programming language we'll use in the course. We expect that you've taken CS 61A, Data 8, or an equivalent class, so we will not be covering general Python syntax. If any of the following exercises are challenging (or if you would like to refresh your Python knowledge), please review one or more of the following materials.

- **[Python Tutorial](https://docs.python.org/3.8/tutorial/)**: Introduction to Python from the creators of Python.
- **[Composing Programs Chapter 1](http://composingprograms.com/pages/11-getting-started.html)**: This is more of a introduction to programming with Python.
- **[Advanced Crash Course](http://cs231n.github.io/python-numpy-tutorial/)**: A fast crash course which assumes some programming background.

### NumPy

NumPy is the numerical computing module introduced in Data 8, which is a prerequisite for this course. Here's a quick recap of NumPy. For more review, read the following materials.

- **[NumPy Quick Start Tutorial](https://numpy.org/doc/stable/user/quickstart.html)**
- **[DS100 NumPy Review](http://ds100.org/fa17/assets/notebooks/numpy/Numpy_Review.html)**
- **[Stanford CS231n NumPy Tutorial](http://cs231n.github.io/python-numpy-tutorial/#numpy)**
- **[The Data 8 Textbook Chapter on NumPy](https://www.inferentialthinking.com/chapters/05/1/Arrays)**

### Question 1

The core of NumPy is the array. Like Python lists, arrays store data; however, they store data in a more efficient manner. In many cases, this allows for faster computation and data manipulation.

__numpy arrays are vectorized__

In Data 8, we used `make_array` from the `datascience` module, but that's not the most typical way. Instead, use `np.array` to create an array. It takes a sequence, such as a list or range. 

Below, create an array `arr` containing the values 1, 2, 3, 4, and 5 (in that order).

<!--
BEGIN QUESTION
name: q1
points: 1
-->

In [21]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [22]:
%%script echo skipping
grader.check("q1")

skipping


In addition to values in the array, we can access attributes such as shape and data type. A full list of attributes can be found [here](https://docs.scipy.org/doc/numpy-1.15.0/reference/arrays.ndarray.html#array-attributes).

In [23]:
arr[3]

4

In [24]:
arr[2:4]

array([3, 4])

In [25]:
arr.shape

(5,)

In [26]:
arr.dtype

dtype('int64')

Arrays, unlike Python lists, cannot store items of different data types.

In [27]:
# A regular Python list can store items of different data types
[1, '3']

[1, '3']

In [28]:
# Arrays will convert everything to the same data type
np.array([1, '3'])
np.array([1, "bill"])

array(['1', 'bill'], dtype='<U21')

In [29]:
# Another example of array type conversion
np.array([5, 8.3])

array([5. , 8.3])

Arrays are also useful in performing *vectorized operations*. Given two or more arrays of equal length, arithmetic will perform element-wise computations across the arrays. 

For example, observe the following:

In [30]:
# Python list addition will concatenate the two lists
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [31]:
# NumPy array addition will add them element-wise
np.array([1, 2, 3]) + np.array([4, 5, 6])

array([5, 7, 9])

### Question 2

#### Question 2a

Write a function `summation` that evaluates the following summation for $n \geq 1$:

$$\sum_{i=1}^{n} i^3 + 3 i^2$$

**Note**: You should not use `for` loops in your solution. Check the [NumPy documentation](https://numpy.org/doc/1.19/reference/index.html). If you're stuck, try a search engine! Searching the web for examples of how to use modules is very common in data science.

<!--
BEGIN QUESTION
name: q2a
points: 1
-->

In [32]:
n = 10
ist = np.arange(1,n+1)

(ist**3 + 3*ist**2).sum()

np.sum(ist**3 + 3*ist**2)



4180

In [33]:
## first try without vectorized numpy arrays (i.e. use a for loop)

s = 0
n = 10


for i in range(1,n+1):
  print(i,s)
  s += i**3 + 3*i**2

s


1 0
2 4
3 24
4 78
5 190
6 390
7 714
8 1204
9 1908
10 2880


4180

In [34]:
## with arrays
n=10
arr = np.arange(1, n+1)
print(arr)
print(arr**2)    ## squares each element
print(arr + arr**2)   ##adds each element of the original array to the square of each element
print(arr**3 + 3*arr**2)  ## gives us the value for each evaluation of the needed sum!

print(np.sum(arr**3 + 3*arr**2))  ## sums the elements of the new list
print(sum(arr**3 + 3*arr**2))     ## not sure what the difference is here between sum and np.sum




[ 1  2  3  4  5  6  7  8  9 10]
[  1   4   9  16  25  36  49  64  81 100]
[  2   6  12  20  30  42  56  72  90 110]
[   4   20   54  112  200  324  490  704  972 1300]
4180
4180


In [35]:
def summation(n):
    """Compute the summation i^3 + 3 * i^2 for 1 <= i <= n."""
    np.arange(1,n+1)
    return sum(arr**3 + 3*arr**2)

summation(10)    

4180

In [36]:
%%script echo skipping
grader.check("q2a")

skipping


#### Question 2b

Write a function `elementwise_array_sum` that computes the square of each value in `list_1`, the cube of each value in `list_2`, then returns a list containing the element-wise sum of these results. Assume that `list_1` and `list_2` have the same number of elements, do not use for loops.

The input parameters will both be **python lists**, so you may need to convert the lists into arrays before performing your operations. The output should be a **numpy array.**

Video 4: https://www.youtube.com/watch?v=FYYuFHtfMME&list=PLQCcNQgUcDfrhStFqvgpvLNhOS43bnSQq&index=4

Video 5: https://www.youtube.com/watch?v=kR09cYndKzE&list=PLQCcNQgUcDfrhStFqvgpvLNhOS43bnSQq&index=5


<!--
BEGIN QUESTION
name: q2b
points: 1
-->

In [37]:
def elementwise_array_sum(list_1, list_2):
    """Compute x^2 + y^3 for each x, y in list_1, list_2. 
    
    Assume list_1 and list_2 have the same length.
    
    Return a NumPy array.
    """
    assert len(list_1) == len(list_2), "both args must have the same number of elements"

    return list_1**2 + list_2**3
    ...

In [38]:
ist1 = np.array([1,1,1,1])
ist2 = np.array([2,2,2,2])

ist2

ist1**2 + ist2**3

array([9, 9, 9, 9])

In [39]:
%%script echo skipping
grader.check("q2b")

skipping


You might have been told that Python is slow, but array arithmetic is carried out very fast, even for large arrays. Below is an implementation of the above code that does not use NumPy arrays.

In [40]:
def elementwise_list_sum(list_1, list_2):
    """Compute x^2 + y^3 for each x, y in list_1, list_2. 
    
    Assume list_1 and list_2 have the same length.
    """

    return [x ** 2 + y ** 3 for x, y in zip(list_1, list_2)]

For ten numbers, `elementwise_list_sum` and `elementwise_array_sum` both take a similar amount of time.

In [41]:
sample_list_1 = list(range(10))
sample_array_1 = np.arange(10)

In [42]:
%%time
elementwise_list_sum(sample_list_1, sample_list_1)

CPU times: user 32 µs, sys: 0 ns, total: 32 µs
Wall time: 38.9 µs


[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]

In [43]:
%%time
elementwise_array_sum(sample_array_1, sample_array_1)

CPU times: user 57 µs, sys: 8 µs, total: 65 µs
Wall time: 71 µs


array([  0,   2,  12,  36,  80, 150, 252, 392, 576, 810])

The time difference seems negligible for a list/array of size 10; depending on your setup, you may even observe that `elementwise_list_sum` executes faster than `elementwise_array_sum`! However, we will commonly be working with much larger datasets:

In [44]:
sample_list_2 = list(range(100000))
sample_array_2 = np.arange(100000)

In [45]:
%%time
elementwise_list_sum(sample_list_2, sample_list_2)
; # The semicolon hides the output

CPU times: user 69.1 ms, sys: 4.37 ms, total: 73.5 ms
Wall time: 76.5 ms


'# The semicolon hides the output'

In [46]:
%%time
elementwise_array_sum(sample_array_2, sample_array_2)
;

CPU times: user 3.38 ms, sys: 0 ns, total: 3.38 ms
Wall time: 3.25 ms


''

With the larger dataset, we see that using NumPy results in code that executes over 50 times faster! Throughout this course (and in the real world), you will find that writing efficient code will be important; arrays and vectorized operations are the most common way of making Python programs run quickly.

#### Question 2c
Recall the formula for population variance below:

$$\sigma^2 = \frac{\sum_{i=1}^N (x_i - \mu)^2}{N}$$

Complete the functions below to compute the population variance of `population`, an array of numbers. For this question, **do not use built in NumPy functions, such as `np.var`.** Again, avoid using `for` loops!

<!--
BEGIN QUESTION
name: q2c
points: 1
-->

In [47]:
def mean(population):
    """
    Returns the mean of population (mu)
    
    Keyword arguments:
    population -- a numpy array of numbers
    """
    # Calculate the mean of a population

    return np.sum(population)/len(population)
    ...

def variance(population):
    """
    Returns the variance of population (sigma squared)
    
    Keyword arguments:
    population -- a numpy array of numbers
    """
    # Calculate the variance of a population

    return np.sum((population - mean(population))**2)/len(population)
    ...

In [48]:
# first working it out manualy
ist = np.array([2,2,4,4])

avg = np.sum(ist)/len(ist)

print(avg)

np.sum((ist-avg)**2)/len(ist)



3.0


1.0

In [49]:
# calling the functions
ist = [1,2,3,4,5,6,7,8,9,10,11,12,13]
arr = np.array(ist)

## my attempt at working to make a file in githup to pump through this function
# bill = pd.read_csv("https://raw.githubusercontent.com/archenclan/dsKal100/main/lab/lab01/var_check.csv")
# #https://raw.githubusercontent.com/archenclan/dsKal100/main/lab/lab01/var_check.csv

# bill
# arr = bill["sample"].to_numpy()
print(arr)
variance(arr)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13]


14.0

In [50]:
%%script echo skipping
grader.check("q2c")

skipping


#### Question 2d

Given the array `random_arr`, assign `valid_values` to an array containing all values $x$ such that $2x^4 > 1$.

**Note**: You should not use `for` loops in your solution. Instead, look at `numpy`'s documentation on [Boolean Indexing](https://numpy.org/devdocs/reference/arrays.indexing.html). 

<!--
BEGIN QUESTION
name: q2d
points: 1
-->

In [51]:
np.random.seed(42)
random_arr = np.random.rand(60)
valid_values = random_arr[2*random_arr**4 > 1]
valid_values

array([0.95071431, 0.86617615, 0.96990985, 0.94888554, 0.96563203,
       0.9093204 , 0.96958463, 0.93949894, 0.89482735, 0.92187424])

In [52]:
#manually working it out
np.random.seed(42)
random_arr = np.random.rand(10)
print(random_arr)
bill = 2*random_arr**4
print(bill)
print(bill[bill > 1])  #this is the all of the bill entries above 1
print(random_arr[bill >1])  #this is all the random_arr entries that correspond to bill > 1

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]
[3.93571255e-02 1.63391746e+00 5.74195709e-01 2.56889624e-01
 1.18504803e-03 1.18431538e-03 2.27637844e-05 1.12578348e+00
 2.61132118e-01 5.02737287e-01]
[1.63391746 1.12578348]
[0.95071431 0.86617615]


In [53]:
%%script echo skipping

grader.check("q2d")

skipping


---
## Part 3: Plotting
Here we explore plotting using `matplotlib` and `numpy`.

### Question 3 ###


Consider the function $f(x) = x^2$ for $-\infty < x < \infty$.

#### Question 3a ####
Find the equation of the tangent line to $f$ at $x = 0$.

Use LaTeX to type your solution, such that it looks like the serif font used to display the math expressions in the sentences above.

**HINT**: You can click any text cell to see the raw Markdown syntax. 

<!--
BEGIN QUESTION
name: q3a
-->

_Type your answer here, replacing this text._

$$f'(x) = 2x$$

therefore:

$$y = mx + b = 0x + 0 = 0$$

#### Question 3b ####
Find the equation of the tangent line to $f$ at $x = 8$. Please use LaTeX to type your solution.

<!--
BEGIN QUESTION
name: q3b
-->

_Type your answer here, replacing this text._

The slope of the tangent at _x_ = 8 is equal to the first derivative:

$$m = f'(x) = f'(8) = 2(8) = 16$$

The _y-intercept_ is the _y_ value at _x_ = 0:

$$16 = \frac{y_2-y_1}{x_2-x_1} = \frac{8^2 - b}{8-0}$$

$$b = 8^2 - 8(16) = -64$$

$$\therefore y = 16x - 64$$

#### Question 3c #### 

Write code to plot the function $f$, the tangent line at $x=8$, and the tangent line at $x=0$. 

Set the range of the x-axis to (-15, 15) and the range of the y-axis to (-100, 300) and the figure size to (4,4).

Your resulting plot should look like this (it's okay if the colors in your plot don't match with ours, as long as they're all different colors):

<img src="https://github.com/archenclan/dsKal100/blob/main/lab/lab01/derivative.png?raw=1" align="center"/>

You should use the `plt.plot` function to plot lines. You may find the following functions useful:

- [`plt.plot(..)`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html)
- [`plt.figure(figsize=..)`](https://stackoverflow.com/questions/332289/how-do-you-change-the-size-of-figures-drawn-with-matplotlib)
- [`plt.ylim(..)`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.ylim.html)
- [`plt.axhline(..)`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.axhline.html)

<!--
BEGIN QUESTION
name: q3c
-->

In [ ]:
def f(x):
    ...
    
def df(x):
    ...

def plot(f, df):              
    ...

plot(f, df)

### Question 4 (Ungraded) ##

Data science is a rapidly expanding field and no degree program can hope to teach you everything that will be helpful to you as a data scientist. So it's important that you become familiar with looking up documentation and learning how to read it. 

Below is a section of code that plots a three-dimensional "wireframe" plot. You'll see what that means when you draw it. Replace each `# Your answer here` with a description of what the line above does, what the arguments being passed in are, and how the arguments are used in the function. For example,

```
np.arange(2, 5, 0.2)
# This returns an array of numbers from 2 to 5 with an interval size of 0.2
```

**Hint:** The `Shift` + `Tab` tip from earlier in the notebook may help here. Remember that objects must be defined in order for the documentation shortcut to work; for example, all of the documentation will show for method calls from `np` since we've already executed `import numpy as np`. However, since `z` is not yet defined in the kernel, `z.reshape(x.shape)` will not show documentation until you run the line `z = np.cos(squared)`.

<!--
BEGIN QUESTION
name: q4
-->

In [83]:
from mpl_toolkits.mplot3d import axes3d

u = np.linspace(1.5 * np.pi, -1.5 * np.pi, 100)
# generates a array of 100 numbers from 1.5*3.14 to -1.5*3.14, inclusive
u
x1 = np.linspace(1,10, num=10)
x2 = np.linspace(21,24, num = 4)
x1
x, y = np.meshgrid(x1, x2)
x
y

# returns two matrices, x with len(x2) rows of x1 array, y with len(x1) columns of x2 array

[x, y] = np.meshgrid(u, u)

squared = np.sqrt(x.flatten() ** 2 + y.flatten() ** 2)
# flatten takes matrix and binds rows together end to end into one array

z = np.cos(squared)
# returns an array of the cosines of each squared element
z = z.reshape(x.shape) #x shape is 4 rows and 10 cols
# shapes the z array into a matrix of 10 columns and 4 rows

fig = plt.figure(figsize = (6, 6))
ax = fig.add_subplot(111, projection = '3d')
# Your answer here
ax.plot_wireframe(x, y, z, rstride = 5, cstride = 5, lw = 2)
# Your answer here
ax.view_init(elev = 60, azim = 25)
# Your answer here
plt.savefig("figure1.png")
# Your answer here

(4, 10)

In [66]:
x1 = np.linspace(1,10, num=10)
x2 = np.linspace(21,24, num = 4)
x1
x, y = np.meshgrid(x1, x2)
x
y


array([[21., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [22., 22., 22., 22., 22., 22., 22., 22., 22., 22.],
       [23., 23., 23., 23., 23., 23., 23., 23., 23., 23.],
       [24., 24., 24., 24., 24., 24., 24., 24., 24., 24.]])

### Question 5 (Ungraded)

Do you think that eating french fries with mayonnaise is a crime?  
Tell us what you think in the following Markdown cell. :)

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [ ]:
grader.check_all()

## Submission

Make sure you have run all cells in your notebook in order before running the cell below, so that all images/graphs appear in the output. The cell below will generate a zip file for you to submit. **Please save before exporting!**

In [ ]:
# Save your notebook first, then run this cell to export your submission.
grader.export(pdf=False)